### ISSUE TITLE
FileList has changed

### ISSUE THREAD

**Issue by ovidiub13** [outkastm/Filelist.ro#10]
Something changed in Filelist. This plugin doesn't work anymore:

```
01-06 23:18:40 ERROR[31mFailed encoding stuff to log "Failed getting results from Filelist: Traceback (most recent call last): File "/config/data/custom_plugins/filelist/main.py", line 52, in _searchOnTitle torrent_url = self.urls['baseurl'] % download['href'] TypeError: 'NoneType' object has no attribute '__getitem__' ": not enough arguments for format string
01-06 23:18:40 ERROR[ filelist] Failed getting results from Filelist: Traceback (most recent call last): File "/config/data/custom_plugins/filelist/main.py", line 52, in _searchOnTitle torrent_url = self.urls['baseurl'] % download['href'] TypeError: 'NoneType' object has no attribute '__getitem__' 
```

**Comment by simistef** [comment]
i think this plugi isnot maintained anymore

**Comment by outkastm** [comment]
It is maintained as i still use it. Last time i download within it yesterday but i cannot check right now
