### ISSUE TITLE
ERROR [   couchpotato.core.event] Error in event "quality.single", that wasn't caught

### ISSUE THREAD

**Issue by sv2241** [outkastm/Filelist.ro#7]
Current version: 4fad95cd24bffd814572e8fd08c4f2f5d14f59b (2/24/2016, 2:08:09 PM)

05-09 18:32:32 INFO [ie.providers.info.omdbapi] Found: All Things Must Pass: The Rise and Fall of Tower Records (2015)
05-09 18:32:32 INFO [core.media.movie.searcher] Search for All Things Must Pass in 720p ignoring ETA
05-09 18:32:32 INFO [core.media.movie.searcher] Search for All Things Must Pass in 1080p ignoring ETA
05-09 18:32:32 ERROR [   couchpotato.core.event] Error in event "quality.single", that wasn't caught: Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/quality/main.py", line 117, in single
    quality = db.get('quality', identifier, with_doc = True)['doc']
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/libs/CodernityDB/database.py", line 944, in get
    raise RecordNotFound("Not found")
RecordNotFound: Not found
encoding=UTF-8 debug=False args=['--data_dir', '/var/db/couchpotato', '--pid_file', '/var/run/couchpotato/couchpotato.pid', '--daemon'] app_dir=/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer data_dir=/var/db/couchpotato desktop=None options=Namespace(config_file='/var/db/couchpotato/settings.conf', console_log=False, daemon=True, data_dir='/var/db/couchpotato', debug=False, pid_file='/var/run/couchpotato/couchpotato.pid', quiet=False)

**Comment by outkastm** [comment]
no info about the error
